<%  
/*-----------------------------------------------------------------------------
■ 시스템명     : 식재영업/주문관리
■ 프로그램ID   : FMP00080E_T001.jsp
■ 프로그램명   : 주문상품 조회
■ 작성일자     : 2008.01.21
■ 작성자       : 박은규
■ 이력관리     : 2008.01.21
-----------------------------------------------------------------------------*/
%>

<%@ page contentType="text/html; charset=EUC-KR" %>
<%@ include file = "../../sc/main/common.jsp" %>
<%
	try	{
		PlatformRequest platformRequest = this.proc_input(request);
		in_vl = platformRequest.getData().getVariableList();
		in_dl = platformRequest.getData().getDataSetList();

		//sql문 버퍼생성
		StringBuffer sbSql = new StringBuffer();
		//내역조회

        sbSql.append("SELECT /*아이템 검색-FMP00080E_T003_1.jsp*/                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("       T.*      , DECODE(T.FEATURE_NAME_CHK, NULL, U.FEATURE_NAME, T.FEATURE_NAME_CHK||U.FEATURE_NAME) AS FEATURE_NAME      , U.FEATURE_ICON      , DECODE(T.PO_WEEK_STATUS, 'XR', '', T.ITEM_CODE) AS WEEK_ITEM_CODE      , DECODE(T.DANGA_ITEM_CODE, NULL, 'NN', 'FE') AS DANGAWEEK_STATUS   FROM (                                           \n");
        sbSql.append("SELECT A.ITEM_CODE, A.ITEM_NAME, A.ITEM_SIZE, A.PO_UOM, A.UNIT_PRICE, A.UNIT_PRICE AS MARGIN_PRICE                                                                                                                                                                                                                                              \n");
        sbSql.append("     , A.SALE_PRICE, B.DEF_QTY AS PR_QTY, ROUND(A.SALE_PRICE * B.DEF_QTY) AS SALE_AMOUNT                                                                                                                                                                                                                                                        \n");
        sbSql.append("     , '002' AS LINE_STATUS, '마감전' AS CLS_STATUS, NULL AS PR_REMARK                                                                                                                                                                                                                                                                          \n");
        sbSql.append("     , 'S1010957' AS SUBINV_CODE, A.NEED_DATE, B.PRE_NEED_DATE                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("     , A.TAX_CODE, A.CUSTCD, A.CENTER_FLAG                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("     , A.CENTER_CODE, A.POINT_FLAG, 114998 AS PR_UPJANG                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("     , A.UPJANG AS RC_UPJANG, 'N' AS INVAT_FLAG, 'N' AS OUTVAT_FLAG                                                                                                                                                                                                                                                                             \n");
        sbSql.append("     , A.MIN_ORD_QTY, A.MAX_ORD_QTY, A.MULTIPLIER_QTY                                                                                                                                                                                                                                                                                           \n");
        sbSql.append("     , A.OTCUSTCD                                                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("     , CASE WHEN CC.OP_PRICE IS NOT NULL OR CC.OP_RATE IS NOT NULL                                                                                                                                                                                                                                                                              \n");
        sbSql.append("            THEN DECODE(SIGN(NVL(CC.OP_PRICE,0) ),0, SCC_CEIL(A.SALE_PRICE + (A.SALE_PRICE * NVL(CC.OP_RATE,0) / 100),CC.CEIL_VAL), CC.OP_PRICE)                                                                                                                                                                                                \n");
        sbSql.append("            WHEN DD.OP_PRICE IS NOT NULL OR DD.OP_RATE IS NOT NULL                                                                                                                                                                                                                                                                              \n");
        sbSql.append("            THEN DECODE(SIGN(NVL(DD.OP_PRICE,0) ),0, SCC_CEIL(A.SALE_PRICE + (A.SALE_PRICE * NVL(DD.OP_RATE,0) / 100),DD.CEIL_VAL), DD.OP_PRICE)                                                                                                                                                                                                \n");
        sbSql.append("       ELSE A.SALE_PRICE END AS OP_PRICE                                                                                                                                                                                                                                                                                                        \n");
        sbSql.append("     , DECODE(CC.OP_RATE, NULL, DD.OP_RATE, CC.OP_RATE) AS OP_RATE                                                                                                                                                                                                                                                                              \n");
        sbSql.append("     , ROUND(CASE WHEN CC.OP_PRICE IS NOT NULL OR CC.OP_RATE IS NOT NULL                                                                                                                                                                                                                                                                        \n");
        sbSql.append("                  THEN DECODE(SIGN(NVL(CC.OP_PRICE,0) ),0, SCC_CEIL(A.SALE_PRICE + (A.SALE_PRICE * NVL(CC.OP_RATE,0) / 100),CC.CEIL_VAL), CC.OP_PRICE)                                                                                                                                                                                          \n");
        sbSql.append("                  WHEN DD.OP_PRICE IS NOT NULL OR DD.OP_RATE IS NOT NULL                                                                                                                                                                                                                                                                        \n");
        sbSql.append("                  THEN DECODE(SIGN(NVL(DD.OP_PRICE,0) ),0, SCC_CEIL(A.SALE_PRICE + (A.SALE_PRICE * NVL(DD.OP_RATE,0) / 100),DD.CEIL_VAL), DD.OP_PRICE)                                                                                                                                                                                          \n");
        sbSql.append("             ELSE A.SALE_PRICE END * B.DEF_QTY) AS OP_AMOUNT                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("     , ROUND(CASE WHEN CC.OP_PRICE IS NOT NULL OR CC.OP_RATE IS NOT NULL                                                                                                                                                                                                                                                                        \n");
        sbSql.append("                  THEN DECODE(SIGN(NVL(CC.OP_PRICE,0) ),0, SCC_CEIL(A.SALE_PRICE + (A.SALE_PRICE * NVL(CC.OP_RATE,0) / 100),CC.CEIL_VAL), CC.OP_PRICE)                                                                                                                                                                                          \n");
        sbSql.append("                  WHEN DD.OP_PRICE IS NOT NULL OR DD.OP_RATE IS NOT NULL                                                                                                                                                                                                                                                                        \n");
        sbSql.append("                  THEN DECODE(SIGN(NVL(DD.OP_PRICE,0) ),0, SCC_CEIL(A.SALE_PRICE + (A.SALE_PRICE * NVL(DD.OP_RATE,0) / 100),DD.CEIL_VAL), DD.OP_PRICE)                                                                                                                                                                                          \n");
        sbSql.append("             ELSE A.SALE_PRICE END / A.KG_CONVERT_RATE / 1000,1) AS G_PRICE                                                                                                                                                                                                                                                                     \n");
        sbSql.append("     , 0 AS OP_AMOUNT_OLD                                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("     , FMS_PREORDER_FUN(A.CENTER_CODE,A.ITEM_CODE,'D_DAYS') AS D_DAYS                                                                                                                                                                                                                                                                           \n");
        sbSql.append("     , A.D_TIMES                                                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("     , 'D-'||FMS_PREORDER_FUN(A.CENTER_CODE,A.ITEM_CODE,'D_DAYS') AS D_DAY_DISP                                                                                                                                                                                                                                                                 \n");
        sbSql.append("     , D.OTCUSTNM, A.KG_CONVERT_RATE                                                                                                                                                                                                                                                                                                            \n");
        sbSql.append("     , NULL AS FEATURE_NAME_CHK                                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("     , A.IMAGE_PATH, DECODE(A.IMAGE_PATH,NULL,'N','Y') AS IMAGE_YN                                                                                                                                                                                                                                                                              \n");
        sbSql.append("     , A.CONSUM_YN, B.PR_ID, A.KEEPING_TYPE                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("     , A.APPLY_SD, A.VD_SN                                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("     , A.ORIGIN_TYPE                                                                                                                                                                                                                                                                                                                            \n");
        sbSql.append("     , 'P' AS MOBILE_GUBUN                                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("     , SCC_SOPR_AGG_FUN('S1010957', A.ITEM_CODE, '1') AS MAX_SO_QTY                                                                                                                                                                                                                                                                             \n");
        sbSql.append("     , SCC_SOPR_AGG_FUN('S1010957', A.ITEM_CODE, '3') AS TOT_SO_AMT                                                                                                                                                                                                                                                                             \n");
        sbSql.append("     , A.UPJANG_GRP                                                                                                                                                                                                                                                                                                                             \n");
        sbSql.append("     , DECODE(A.OTCUSTCD, '0000', EPROCUSR.FN_ITEM_PROCURE_SCH('100', 'HFC', (SELECT OPER_ORG_SN_PURC FROM HLDC_PO_CENTER WHERE CENTER_CODE = A.CENTER_CODE), A.ITEM_CODE, A.VD_SN, '02', FMS_PREORDER_FUN(A.CENTER_CODE,A.ITEM_CODE,'D_DAYS'), FMS_PREORDER_FUN(A.CENTER_CODE,A.ITEM_CODE,'D_TIMES'), '20160822', '20160824'), 'HK') AS PO_STATUS \n");
        sbSql.append("     , EPROCUSR.FN_ITEM_PROCURE_MTG_UNS('100', A.ITEM_CODE) AS UNUSE_YN                                                                                                                                                                                                                                                                         \n");
        sbSql.append("     , EPROCUSR.FN_ITEM_PROCURE_MTG_STP('100', A.ITEM_CODE, '02') AS VAL_STP_YN                                                                                                                                                                                                                                                                 \n");
        sbSql.append("     , DECODE(A.OTCUSTCD, '0000', FMP_ORDER_SCHL_FUN(131023, A.CUSTCD, A.ITEM_CODE, '20160824'), 'N') AS FMP_STATUS                                                                                                                                                                                                                             \n");
        sbSql.append("     , DECODE(A.OTCUSTCD, '0000', EPROCUSR.FN_ITEM_PROCURE_REQ_WKD('100', 'HFC', (SELECT OPER_ORG_SN_PURC FROM HLDC_PO_CENTER WHERE CENTER_CODE = A.CENTER_CODE), A.ITEM_CODE, A.VD_SN, '02', '20160824'), 'XR') AS PO_WEEK_STATUS , DANGA_ITEM_CODE                                                                                            \n");
        sbSql.append("  FROM                                                                                                                                                                                                                                                                                                                                          \n");
        sbSql.append("       (                                                                                                                                                                                                                                                                                                                                        \n");
        sbSql.append("       SELECT *                                                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("         FROM FMU_OP_RATE                                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("        WHERE UPJANG = 131023                                                                                                                                                                                                                                                                                                                   \n");
        sbSql.append("          AND '20160824' BETWEEN SDATE AND EDATE                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("          AND USE_YN = 'Y'                                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("          AND ITEM_TYPE = 'M'                                                                                                                                                                                                                                                                                                                   \n");
        sbSql.append("       ) CC                                                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("      ,(                                                                                                                                                                                                                                                                                                                                        \n");
        sbSql.append("       SELECT *                                                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("         FROM FMU_OP_RATE                                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("        WHERE UPJANG = 131023                                                                                                                                                                                                                                                                                                                   \n");
        sbSql.append("          AND '20160824' BETWEEN SDATE AND EDATE                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("          AND USE_YN = 'Y'                                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("          AND ITEM_TYPE = 'C'                                                                                                                                                                                                                                                                                                                   \n");
        sbSql.append("       ) DD                                                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("     , FMP_OTHER_CUST D , FMP_OTCUST_LINK F                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("     ,(SELECT 0 AS DEF_QTY, '' AS PR_ID, '' AS PRE_NEED_DATE  FROM DUAL) B                                                                                                                                                                                                                                                                      \n");
        sbSql.append("     ,(SELECT 131023 AS UPJANG                                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("            , '20160824' AS NEED_DATE                                                                                                                                                                                                                                                                                                           \n");
        sbSql.append("            , C.CONSUM_YN, C.ITEM_CLASS2, C.ITEM_CLASS3, C.ITEM_CLASS4                                                                                                                                                                                                                                                                          \n");
        sbSql.append("            , A.ITEM_CODE, C.ITEM_NAME, C.ITEM_SIZE, C.PO_UOM                                                                                                                                                                                                                                                                                   \n");
        sbSql.append("            , C.TAX_CODE, A.CUSTCD, A.CENTER_FLAG                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("            , A.CENTER_CODE, C.POINT_FLAG                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("            , A.CONTRACT_PRICE AS UNIT_PRICE                                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("            , A.SALE_PRICE                                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("            , DECODE(C.POINT_FLAG,'Y',DECODE(C.MIN_ORD_QTY,0,0,0.1),C.MIN_ORD_QTY) AS MIN_ORD_QTY                                                                                                                                                                                                                                               \n");
        sbSql.append("            , C.MAX_ORD_QTY                                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("            , DECODE(C.POINT_FLAG,'Y',DECODE(C.MULTIPLIER_QTY,0,0,0.1),C.MULTIPLIER_QTY) AS MULTIPLIER_QTY                                                                                                                                                                                                                                      \n");
        sbSql.append("            , '0000' AS OTCUSTCD                                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("              --디데이날짜와 입고일이 같으면 디타임을 체크하여 넘었으면 디데이 하루 추가                                                                                                                                                                                                                                                        \n");
        sbSql.append(" 	            /* 구매 D_DAYS 사용(기존 +1 삭제) */                                                                                                                                                                                                                                                                                              \n");
        sbSql.append("            , DECODE( SIGN(TO_DATE('20160824','YYYYMMDD') - TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD'),'YYYYMMDD') - NVL(K.D_DAYS,0) )                                                                                                                                                                                                                 \n");
        sbSql.append("                    , 0, DECODE(SIGN(DECODE(K.D_TIMES,'',24,0,24,K.D_TIMES) - TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))),1,0,1)                                                                                                                                                                                                                        \n");
        sbSql.append("                    , 0 ) + NVL(K.D_DAYS,0) AS D_DAYS                                                                                                                                                                                                                                                                                           \n");
        sbSql.append("            , DECODE(K.D_TIMES,'',2400,0,2400,K.D_TIMES*100) AS D_TIMES                                                                                                                                                                                                                                                                         \n");
        sbSql.append("            , C.KG_CONVERT_RATE                                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("            , C.IMG_PATH AS IMAGE_PATH                                                                                                                                                                                                                                                                                                          \n");
        sbSql.append("            , A.DANGA_ITEM_CODE, A.WEEK_ITEM_CODE, C.KEEPING_TYPE                                                                                                                                                                                                                                                                               \n");
        sbSql.append("            , A.APPLY_SD, A.VD_SN                                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("            , C.ORIGIN_TYPE                                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("            , A.UPJANG_GRP                                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("         FROM                                                                                                                                                                                                                                                                                                                                   \n");
        sbSql.append("             (SELECT A.*, NULL AS DANGA_ITEM_CODE, NULL AS WEEK_ITEM_CODE                                                                                                                                                                                                                                                                       \n");
        sbSql.append("                FROM HLDC_PO_CONTRACT_FSALE A                                                                                                                                                                                                                                                                                                   \n");
        sbSql.append("               WHERE 1=1                                                                                                                                                                                                                                                                                                                        \n");
        sbSql.append("               AND (CENTER_CODE, CUSTCD, ITEM_CODE) NOT IN                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("                     (SELECT CENTER_CODE, CUSTCD, ITEM_CODE                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("                        FROM FMP_ORDER_SCHEDULE                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("                       WHERE CENTER_CODE = 300005                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("                         AND UPJANG = 134002                                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("                         AND USE_YN = 'Y'                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("                         AND DECODE(TO_CHAR(TO_DATE('20160824','YYYYMMDD'),'D'),                                                                                                                                                                                                                                                                \n");
        sbSql.append("                                      1,SUN,2,MON,3,TUE,4,WED,5,THU,6,FRI,7,SAT) = 'Y'                                                                                                                                                                                                                                                          \n");
        sbSql.append("                       UNION ALL                                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("                     (SELECT CENTER_CODE, CUSTCD, ITEM_CODE                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("                        FROM FMP_ORDER_SCHEDULE                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("                       WHERE CENTER_CODE = 300005                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("                         AND UPJANG = -2                                                                                                                                                                                                                                                                                                        \n");
        sbSql.append("                         AND USE_YN = 'Y'                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("                         AND DECODE(TO_CHAR(TO_DATE('20160824','YYYYMMDD'),'D'),                                                                                                                                                                                                                                                                \n");
        sbSql.append("                                      1,SUN,2,MON,3,TUE,4,WED,5,THU,6,FRI,7,SAT) = 'Y'                                                                                                                                                                                                                                                          \n");
        sbSql.append("                       MINUS                                                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("                      SELECT CENTER_CODE, CUSTCD, ITEM_CODE                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("                        FROM FMP_ORDER_SCHEDULE                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("                       WHERE CENTER_CODE = 300005                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("                         AND UPJANG = 134002                                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("                         AND USE_YN = 'Y'                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("                         AND DECODE(TO_CHAR(TO_DATE('20160824','YYYYMMDD'),'D'),                                                                                                                                                                                                                                                                \n");
        sbSql.append("                                      1,SUN,2,MON,3,TUE,4,WED,5,THU,6,FRI,7,SAT) = 'Y'))                                                                                                                                                                                                                                                        \n");
        sbSql.append("              	   AND A.CENTER_CODE = 300005                                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("              	   AND A.UPJANG = 134002                                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("                     AND '20160824' BETWEEN A.CONTRACT_START AND NVL(A.CONTRACT_END, '99999999')                                                                                                                                                                                                                                                \n");
        sbSql.append("                     AND EXISTS (SELECT 1 FROM HLDC_PO_CONTRACT_F WHERE CENTER_CODE = A.CENTER_CODE AND UPJANG = A.UPJANG AND ITEM_CODE = A.ITEM_CODE AND CONTRACT_PRICE > 0 AND '20160824' BETWEEN CONTRACT_START AND CONTRACT_END)                                                                                                            \n");
        sbSql.append("             ) A                                                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("            , HLDC_PO_ITEM_MST C                                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("            , HLDC_PO_PREORDER_LIST K                                                                                                                                                                                                                                                                                                           \n");
        sbSql.append("        WHERE A.ITEM_CODE = C.ITEM_CODE                                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("          AND A.SALE_PRICE > 0                                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("          AND A.USE_YN = 'Y' AND C.USE_YN = 'Y'                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("          AND C.ITEM_CLASS1 = 'F'                                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("          AND C.CONSUM_YN = NVL('N',C.CONSUM_YN)                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("          AND A.CENTER_CODE = K.CENTER_CODE(+)                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("          AND A.ITEM_CODE = K.ITEM_CODE(+)                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("       -----------                                                                                                                                                                                                                                                                                                                              \n");
        sbSql.append("        UNION ALL                                                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("       -----------                                                                                                                                                                                                                                                                                                                              \n");
        sbSql.append("       SELECT 131023 AS UPJANG, '20160824' AS NEED_DATE                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("            , C.CONSUM_YN, C.ITEM_CLASS2, C.ITEM_CLASS3, C.ITEM_CLASS4                                                                                                                                                                                                                                                                          \n");
        sbSql.append("            , A.ITEM_CODE, C.ITEM_NAME, C.ITEM_SIZE, C.PO_UOM                                                                                                                                                                                                                                                                                   \n");
        sbSql.append("            , C.TAX_CODE, 0 AS CUSTCD, 'N' AS CENTER_FLAG                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("            , '0' AS CENTER_CODE, C.POINT_FLAG                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("            , A.UNIT_PRICE                                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("            , A.SALE_PRICE                                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("            , C.MIN_ORD_QTY, C.MAX_ORD_QTY, C.MULTIPLIER_QTY                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("            , C.OTCUSTCD                                                                                                                                                                                                                                                                                                                        \n");
        sbSql.append("              --디데이날짜와 입고일이 같으면 디타임을 체크하여 넘었으면 디데이 하루 추가                                                                                                                                                                                                                                                        \n");
        sbSql.append("            , DECODE( SIGN(TO_DATE('20160824','YYYYMMDD') - TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD'),'YYYYMMDD') - NVL(C.D_DAYS,0) - 1)                                                                                                                                                                                                              \n");
        sbSql.append("                    , 0, DECODE(SIGN(DECODE(C.D_TIMES,'',2400,0,2400,TO_NUMBER(C.D_TIMES)) - TO_NUMBER(TO_CHAR(SYSDATE,'HH24MI'))),1,0,1)                                                                                                                                                                                                       \n");
        sbSql.append("                    , 0 ) + NVL(C.D_DAYS,0) + 1 AS D_DAYS                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("            , DECODE(C.D_TIMES,'',2400,0,2400,TO_NUMBER(C.D_TIMES)) AS D_TIMES                                                                                                                                                                                                                                                                  \n");
        sbSql.append("            , C.KG_CONVERT_RATE                                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("            , C.SIMAGE_PATH AS IMAGE_PATH                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("            , NULL AS DANGA_ITEM_CODE, NULL AS WEEK_ITEM_CODE, C.KEEPING_TYPE                                                                                                                                                                                                                                                                   \n");
        sbSql.append("            , '' AS APPLY_SD, '' AS VD_SN                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("            , C.ORIGIN_TYPE                                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("            , '' AS UPJANG_GRP                                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("         FROM FMP_OTCUST_PRICE_AVA_V A                                                                                                                                                                                                                                                                                                          \n");
        sbSql.append("            ,(SELECT UPJANG, ITEM_CODE, MAX(SDATE) AS SDATE                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("                FROM FMP_OTCUST_PRICE_AVA_V                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("               WHERE UPJANG = 131023                                                                                                                                                                                                                                                                                                            \n");
        sbSql.append("                 AND SDATE <= '20160824'                                                                                                                                                                                                                                                                                                        \n");
        sbSql.append("               GROUP BY UPJANG, ITEM_CODE                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("              ) B                                                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("            , FMP_OTCUST_ITEM C                                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("        WHERE A.UPJANG = B.UPJANG                                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("          AND A.SDATE = B.SDATE                                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("          AND A.ITEM_CODE = B.ITEM_CODE                                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("          AND A.ITEM_CODE = C.ITEM_CODE                                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("          AND A.SALE_PRICE > 0                                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("          AND A.USE_YN = 'Y' AND C.USE_YN = 'Y'                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("          AND C.CONSUM_YN = NVL('N',C.CONSUM_YN)                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("      ) A,                                                                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("      (SELECT ROW_NUMBER() OVER(ORDER BY CD_SY||CD_SM||CD_SD DESC) AS SEQ                                                                                                                                                                                                                                                                       \n");
        sbSql.append("             ,CD_SY||CD_SM||CD_SD AS NONHOLI_DATE                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("         FROM SCC_CALENDA_DATA                                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("        WHERE CD_SY||CD_SM||CD_SD < '20160824'                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("          AND CD_SY BETWEEN TO_NUMBER(SUBSTR('20160824',1,4))-1 AND TO_NUMBER(SUBSTR('20160824',1,4))                                                                                                                                                                                                                                           \n");
        sbSql.append("          AND CD_WEEK NOT IN ('일')) KK                                                                                                                                                                                                                                                                                                         \n");
        sbSql.append(" WHERE A.ITEM_CODE = CC.ITEM_CODE(+)                                                                                                                                                                                                                                                                                                            \n");
        sbSql.append("   AND A.ITEM_CLASS4 = DD.ITEM_CODE(+)                                                                                                                                                                                                                                                                                                          \n");
        sbSql.append("   AND A.D_DAYS = KK.SEQ(+)                                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("   AND A.OTCUSTCD = D.OTCUSTCD                                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("   AND A.ITEM_CLASS2 = NVL('',A.ITEM_CLASS2)                                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("   AND A.ITEM_CLASS3 = NVL('',A.ITEM_CLASS3)                                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("   AND A.ITEM_CLASS4 = NVL('',A.ITEM_CLASS4)                                                                                                                                                                                                                                                                                                    \n");
        sbSql.append("   AND D.OTCUSTCD = F.OTCUSTCD                                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("   AND F.UPJANG = ((SELECT Z.MAIN_UPJANG FROM FMS_UPJANG Z WHERE UPJANG = 131023))                                                                                                                                                                                                                                                              \n");
        sbSql.append("   AND F.USE_YN = 'Y'                                                                                                                                                                                                                                                                                                                           \n");
        sbSql.append("   AND (                                                                                                                                                                                                                                                                                                                                        \n");
        sbSql.append("   		A.ITEM_CODE LIKE '%'||'서리태'||'%'                                                                                                                                                                                                                                                                                                        \n");
        sbSql.append("   	OR  A.ITEM_NAME LIKE '%'||'서리태'||'%'                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("   	OR  A.ITEM_SIZE LIKE '%'||'서리태'||'%'                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("   	 )                                                                                                                                                                                                                                                                                                                                          \n");
        sbSql.append("   AND (SELECT TO_NUMBER(TO_DATE(A.NEED_DATE,'YYYYMMDD') - TO_DATE(Z.NONHOLI_DATE,'YYYYMMDD'))                                                                                                                                                                                                                                                  \n");
        sbSql.append("          FROM (SELECT ROW_NUMBER() OVER(ORDER BY CD_SY||CD_SM||CD_SD DESC) AS SEQ                                                                                                                                                                                                                                                              \n");
        sbSql.append("                     , CD_SY||CD_SM||CD_SD AS NONHOLI_DATE                                                                                                                                                                                                                                                                                      \n");
        sbSql.append("                  FROM SCC_CALENDA_DATA                                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("                 WHERE CD_SY||CD_SM||CD_SD < '20160824'                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("                   AND CD_SY BETWEEN TO_NUMBER(SUBSTR('20160824',1,4))-1 AND TO_NUMBER(SUBSTR('20160824',1,4))                                                                                                                                                                                                                                  \n");
        sbSql.append("                   AND CD_WEEK NOT IN ('일')) Z                                                                                                                                                                                                                                                                                                 \n");
        sbSql.append("         WHERE Z.SEQ = TO_NUMBER(A.D_DAYS)) <= TO_NUMBER(TRIM(TO_CHAR(TO_DATE(A.NEED_DATE,'YYYYMMDD') - TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD'),'YYYYMMDD'),'0000')))                                                                                                                                                                               \n");
        sbSql.append("   AND NOT EXISTS                                                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("      (SELECT 1 FROM FMP_ORD_LIMIT Z                                                                                                                                                                                                                                                                                                            \n");
        sbSql.append("        WHERE Z.UPJANG = A.UPJANG                                                                                                                                                                                                                                                                                                               \n");
        sbSql.append("          AND Z.ITEM_CODE = A.ITEM_CODE                                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("          AND A.NEED_DATE BETWEEN Z.SDATE AND Z.EDATE                                                                                                                                                                                                                                                                                           \n");
        sbSql.append("          AND Z.USE_YN = 'Y')                                                                                                                                                                                                                                                                                                                   \n");
        sbSql.append("        ) T                                                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("      , (SELECT /*+ INDEX(B.MR ESPSSGPITM_PK) */A.ITEM_CODE                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("                , CASE WHEN B.DUTY_YN = 'Y' THEN '기획자재'                                                                                                                                                                                                                                                                                     \n");
        sbSql.append("                       WHEN A.MANUF_CD IS NOT NULL THEN '전처리'                                                                                                                                                                                                                                                                                \n");
        sbSql.append("                       WHEN B.PB_YN = 'Y' THEN 'PB상품'                                                                                                                                                                                                                                                                                         \n");
        sbSql.append("                       WHEN A.ECO_ITEM IN ('유기농','무농약','저농약','무항생제') THEN '친환경'                                                                                                                                                                                                                                                 \n");
        sbSql.append("                       ELSE ''                                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("                   END AS FEATURE_NAME                                                                                                                                                                                                                                                                                                          \n");
        sbSql.append("                , CASE WHEN B.DUTY_YN = 'Y' THEN 'theme://Images/new/grd_WF_Icon11.png'                                                                                                                                                                                                                                                         \n");
        sbSql.append("                       WHEN A.MANUF_CD IS NOT NULL THEN 'theme://Images/new/grd_WF_Icon10.png'                                                                                                                                                                                                                                                  \n");
        sbSql.append("                       WHEN B.PB_YN = 'Y' THEN 'theme://Images/new/grd_WF_Icon09.png'                                                                                                                                                                                                                                                           \n");
        sbSql.append("                       WHEN A.ECO_ITEM IN ('유기농','무농약','저농약','무항생제') THEN 'theme://Images/new/grd_WF_Icon08.png'                                                                                                                                                                                                                   \n");
        sbSql.append("                       ELSE ''                                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("                   END AS FEATURE_ICON                                                                                                                                                                                                                                                                                                          \n");
        sbSql.append("             FROM EPROCUSR.MV_ITEM_MST3 A, EPROCUSR.VO_CONTRACT_F B                                                                                                                                                                                                                                                                             \n");
        sbSql.append("            WHERE A.ITEM_CODE = B.ITEM_CODE(+)                                                                                                                                                                                                                                                                                                  \n");
        sbSql.append("              AND A.USE_YN = 'Y'                                                                                                                                                                                                                                                                                                                \n");
        sbSql.append("              AND B.UPJANG(+) = 131023                                                                                                                                                                                                                                                                                                          \n");
        sbSql.append("              AND '20160824' BETWEEN B.CONTRACT_START(+) AND B.CONTRACT_END(+)                                                                                                                                                                                                                                                                  \n");
        sbSql.append("        ) U                                                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append(" WHERE T.ITEM_CODE = U.ITEM_CODE(+)                                                                                                                                                                                                                                                                                                             \n");
        sbSql.append("   AND T.PO_STATUS = 'HK' AND T.FMP_STATUS = 'N' AND T.PO_WEEK_STATUS = 'XR'                                                                                                                                                                                                                                                                    \n");
        sbSql.append("   AND T.UNUSE_YN <> 'UK'                                                                                                                                                                                                                                                                                                                       \n");
        sbSql.append("   AND T.VAL_STP_YN <> 'TK'                                                                                                                                                                                                                                                                                                                     \n");
        sbSql.append(" ORDER BY DECODE(U.FEATURE_NAME, '기획자재', '1', ''), NVL(T.TOT_SO_AMT, 0) DESC, T.ITEM_CODE                                                                                                                                                                                                                                                   \n");

out_vl.add("fa_Sql", sbSql.toString());
		//System.out.println(sbSql.toString());
		pstmt = conn.prepareStatement(sbSql.toString());		
		rs = pstmt.executeQuery(); 
		//ds_list = this.makeDataSet(rs, "ds_List");
		
		pstmt.close();
		rs.close();

		/**종료**/
		//out_dl.add("ds_List", ds_list);
		//this.setResultMessage(0, "OK", out_vl);

	}
	catch(Exception ex)
	{
		//ex.printStackTrace();
		//jsp 로그남기기
		logger.debug(ex.getMessage(), ex);		
		this.setResultMessage(-1, ex.toString(),out_vl);
	}
	finally
	{
		if(rs != null) {
			try {
				rs.close();
			}catch(Exception e) {}
		}
		if(pstmt != null) {
			try {
				pstmt.close();
			}catch(Exception e) {}
		}
		if(conn != null) {
			try {
				conn.close();
			}catch(Exception e) {}
		}
		//jsp log 서비스 닫기 
		try {
			logger.endIndividualLog();
		} catch( Exception logE) {
			logE.printStackTrace();
		}		
	}

	proc_output(response,out,out_vl,out_dl);

%>
